
spring:
  application:
    name: PHONE-SERVICE
  redis:
    host: localhost
    password:
    port: 6379
    lettuce:
      shutdown-timeout: 30000
      pool:
        max-active: 30
        max-idle: 8
        min-idle: 0
  main:
    allow-bean-definition-overriding: true

